### ISSUE TITLE
minimum postgresql version

### ISSUE THREAD

**Issue by reedstrm** [okbob/session_exec#1]
The latest changes to limit to user sessions broke compiling against postgresql < 9.5 (there is no access/parallel.h ) Just FYI.

We use this to preload the python interpreter, and set it up to use a specific virtualenv with that interpreter.
I don't _think_ limiting to user sessions will break that usecase, but I'm slightly worried that it might. Do parallelworkers ever run user-defined functions?

**Comment by okbob** [comment]
I am not sure, but when I check the source code, then there is comment
<pre>
/* ----------------------------------------------------------------
 * PostgresMain
 *<>   postgres main loop -- all backends, interactive or otherwise start here
 *
</pre>

There is start of 
<pre>
<-->/*
<--> * process any libraries that should be preloaded at backend start (this
<--> * likewise can't be done until GUC settings are complete)
<--> */
<-->process_session_preload_libraries();
</pre>

The compilation should be fixed now
