### ISSUE TITLE
too many arguments to function ‘FuncnameGetCandidates’

### ISSUE THREAD

**Issue by javaCR7** [okbob/session_exec#2]
when I do "make" command. it has a mistake which 
"session_exec.c:56:2: error: too many arguments to function ‘FuncnameGetCandidates’
  clist = FuncnameGetCandidates(names, 0, NIL, false, false, true);"
it require six arguments,but
the  function 'funcnameGetCandidates' in file 'namespace.h' has five arguments.

what's the problems ,or which  boo arguments i  could delete?
https://file.nj.zhihuiweijian.com/namespace.png
https://file.nj.zhihuiweijian.com/error.png

**Comment by okbob** [comment]
should be fixed now

**Comment by javaCR7** [comment]
it's still the same mistake

**Comment by okbob** [comment]
what version of Postgres do you use?

**Comment by javaCR7** [comment]
10.1



---Original---
From: "Pavel ***@***.***&gt;
Date: Wed, Nov 17, 2021 13:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [okbob/session_exec] too many arguments to function ‘FuncnameGetCandidates’ (Issue #2)




 
what version of Postgres do you use?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by okbob** [comment]
st 17. 11. 2021 v 6:14 odesílatel javaCR7 ***@***.***> napsal:

> 10.1
>
>
>
> ---Original---
> From: "Pavel ***@***.***&gt;
> Date: Wed, Nov 17, 2021 13:07 PM
> To: ***@***.***&gt;;
> Cc: ***@***.******@***.***&gt;;
> Subject: Re: [okbob/session_exec] too many arguments to function
> ‘FuncnameGetCandidates’ (Issue #2)
>
>
>
>
It is strange. I can build without any problem. It looks like there are
some problems in your development environment. Maybe your development files
(header files) are older than you think.

**Comment by javaCR7** [comment]
I installed  10.3 postgresql  in  new centos os，it's still the same error.Are you sure this error is due to a  version of database problem?

**Comment by javaCR7** [comment]
what's the 'header files'?

**Comment by okbob** [comment]
po 22. 11. 2021 v 10:53 odesílatel javaCR7 ***@***.***>
napsal:

> I installed 10.3 postgresql in new centos os，it's still the same error.Are
> you sure this error is due to a version of database problem?
>
It depends on your build environment. I rechecked it now, and the
compilation for Pg 10 is without any problem.

Theoretically there can be a problem, because I do build against Postgres
10.19, but it has very low probability.
gcc -Wall -Wmissing-prototypes -Wpointer-arith
-Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
-Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
-Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC -I. -I./
-I/usr/local/pgsql/10/include/server -I/usr/local/pgsql/10/include/internal
 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o session_exec.o session_exec.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith
-Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
-Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
-Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC -shared -o
session_exec.so session_exec.o  -L/usr/local/pgsql/10/lib
 -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/10/lib',--enable-new-dtags
[sudo] heslo pro pavel:
/usr/bin/mkdir -p '/usr/local/pgsql/10/lib'

**Comment by okbob** [comment]
po 22. 11. 2021 v 11:22 odesílatel javaCR7 ***@***.***>
napsal:

> what's the 'header files'?
>
all header files related to Postgres.

see https://dba.stackexchange.com/a/192728/6012

**Comment by javaCR7** [comment]
session_preload_libraries = 'session_exec'
session_exec.login_name='login'

I done this setting in postgresql.conf.
the  login function does not work when I login  failed.
but it excuted sucess when I manual eccuted the login function.
I think it does not works for  the setting" session_exec.login_name='login'"
Whether additional configuration is required？

**Comment by okbob** [comment]
út 23. 11. 2021 v 10:55 odesílatel javaCR7 ***@***.***>
napsal:

> session_preload_libraries = 'session_exec'
> session_exec.login_name='login'
>
> I done this setting in postgresql.conf.
> the login function does not work when I login failed.
> but it excuted sucess when I manual eccuted the login function.
> I think it does not works for the setting" session_exec.login_name='login'"
> Whether additional configuration is required？
>

that is all
